version: '3'

services:
  redis:
    image: redis:6.2.6
    restart: always
    container_name: redis
    ports:
      - "6379:6379"
    command: redis-server --save 20 1 --loglevel warning
    volumes:
      - cache:/data

  database:
    image: postgres:13-alpine3.16
    restart: always
    env_file:
      - postgres/.env
    volumes:
      - ./postgres/init_data_prod/:/docker-entrypoint-initdb.d/
      - ./postgres/data:/var/lib/postgresql/data/
    ports:
      - 5432:5432

  elastic:
    image: elasticsearch:7.17.4
    restart: always
    container_name: elastic
    ports:
      - "9200:9200"
    volumes:
      - ./elastic_index/data:/usr/share/elasticsearch/data
    environment:
      discovery.type: single-node
      ES_JAVA_OPTS: -Xms200m -Xmx200m

volumes:
  static_volume:
    external: true
  cache:
    driver: local
  esdata:
    external: true