PERSONS_INDEX_NAME = 'test_persons'
PERSONS_DATA_PATH_NAME = 'persons'

MOVIES_INDEX_NAME = 'test_movies'
MOVIES_DATA_PATH_NAME = 'movies'

GENRES_INDEX_NAME = 'test_genres'
GENRES_DATA_PATH_NAME = 'genres'

INDEX_PATHNAME = {
    PERSONS_INDEX_NAME: PERSONS_DATA_PATH_NAME,
    MOVIES_INDEX_NAME: MOVIES_DATA_PATH_NAME,
    # GENRES_INDEX_NAME: GENRES_DATA_PATH_NAME,
}
